"""empty message

Revision ID: d8b7cdbc551a
Revises: 0685b20b6790
Create Date: 2023-12-05 23:31:01.943311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b7cdbc551a'
down_revision = '0685b20b6790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
