"""empty message

Revision ID: 806406f4079f
Revises: d8b7cdbc551a
Create Date: 2023-12-05 23:38:38.562351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '806406f4079f'
down_revision = 'd8b7cdbc551a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_order',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='likes_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='likes_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name='likes_pkey')
    )
    op.drop_table('product_order')
    # ### end Alembic commands ###
